### ISSUE TITLE
USER STORY: Editing a Comment

### ISSUE THREAD

**Issue by laurachri-hall** [laurachri-hall/LitRPG-Library#7]
As a **comment author** I can **edit my comments** so that **I can update or correct information**.

### Acceptance Criteria
- COmment authors see an edit option on their own comments
- clicking edit allows inline editing of the comment text
- users can save changes updating hte ocmment content
- edited comments display an edited indicator

### Tasks
- [x] Add an "Edit" button next to each comment for the author.
- [x] Implement inline editing when the "Edit" button is clicked.
- [x] Add a "Save" button to save changes to the comment.
- [x] Update the comment in the database upon saving.
